import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./hooks/useAuth";
import { CartProvider } from './hooks/useCart';
import { AdminProvider } from './hooks/useAdmin';




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AdminProvider>
            <CartProvider>
              <header>
                <Navbar />
              </header>
              <body className={inter.className}>{children}</body>
            </CartProvider>
          </AdminProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
