import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./hooks/useAuth";
import { CartProvider } from './hooks/useCart.js';
import { AdminProvider } from './hooks/useAdmin';

import { Inter, Roboto_Mono } from 'next/font/google'
 
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
 
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto_mono.variable}`}>
      <body>
        <AuthProvider>
          <AdminProvider>
            <CartProvider>
              <header>
                <Navbar />
              </header>
              <body className={inter.className}>{children}</body>
            </CartProvider>
          </AdminProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
